import type { Metadata } from "next";
import "./globals.css";

import { inter } from "@/app/ui/fonts";
import Header from "@/app/ui/components/header";
import SideNav from "@/app/ui/components/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Header />
        <SideNav />
        <div className="ml-48">
          {children}
        </div>
      </body>
    </html>
  );
}
